-- Complete VisionGuard Schema Update
-- Adding missing tables and extending existing ones for the SaaS transformation

-- 1. Extend Profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS avatar TEXT,
ADD COLUMN IF NOT EXISTS organization TEXT,
ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'UTC';

-- 2. User Settings
CREATE TABLE IF NOT EXISTS public.user_settings (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  theme TEXT DEFAULT 'light',
  dark_mode BOOLEAN DEFAULT false,
  density TEXT DEFAULT 'comfortable',
  dashboard_layout JSONB DEFAULT '{}'::jsonb,
  email_alerts BOOLEAN DEFAULT true,
  system_alerts BOOLEAN DEFAULT true,
  incident_alerts BOOLEAN DEFAULT true,
  report_notifications BOOLEAN DEFAULT true,
  default_landing_page TEXT DEFAULT '/app',
  favorite_cameras JSONB DEFAULT '[]'::jsonb,
  saved_filters JSONB DEFAULT '{}'::jsonb,
  analytics_presets JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Update Cameras
ALTER TABLE public.cameras
ADD COLUMN IF NOT EXISTS health_score INT DEFAULT 100,
ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW();

-- 4. Incidents (replaces/extends violations conceptually, but we will create a dedicated incidents table)
CREATE TABLE IF NOT EXISTS public.incidents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_type TEXT NOT NULL,
  severity TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  location TEXT,
  description TEXT,
  assigned_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  camera_id UUID REFERENCES public.cameras(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

-- 5. Extend Alerts
ALTER TABLE public.alerts
ADD COLUMN IF NOT EXISTS title TEXT,
ADD COLUMN IF NOT EXISTS severity TEXT DEFAULT 'warning',
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS description TEXT;

-- 6. Reports
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  format TEXT NOT NULL,
  size TEXT,
  file_url TEXT,
  generated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Notifications (User specific alerts)
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Audit Logs (Replaces/Extends activity_logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  metadata JSONB,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Apply RLS Policies for new tables

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- User Settings: Users can read/update their own settings
CREATE POLICY "Users can manage their own settings" 
ON public.user_settings FOR ALL TO authenticated 
USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Incidents: Readable by all authenticated. Modified by Operators/Admins
CREATE POLICY "Incidents are readable by all" 
ON public.incidents FOR SELECT TO authenticated USING (true);

CREATE POLICY "Incidents modifiable by operators and admins" 
ON public.incidents FOR ALL TO authenticated 
USING (auth_user_role() IN ('Operator', 'Supervisor', 'Admin'));

-- Reports: Readable by all
CREATE POLICY "Reports are readable by all" 
ON public.reports FOR SELECT TO authenticated USING (true);

CREATE POLICY "Reports can be generated by operators and admins" 
ON public.reports FOR INSERT TO authenticated 
WITH CHECK (auth_user_role() IN ('Operator', 'Supervisor', 'Admin'));

-- Notifications: Only owner can see/modify
CREATE POLICY "Notifications belong to user" 
ON public.notifications FOR ALL TO authenticated 
USING (auth.uid() = user_id);

-- Audit Logs: Insertable by system/users, viewable by admins
CREATE POLICY "Audit logs insertable by authenticated users" 
ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Audit logs readable by admins" 
ON public.audit_logs FOR SELECT TO authenticated 
USING (auth_user_role() = 'Admin');

-- Settings Auto-Creation Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user_settings()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_settings (id) VALUES (NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created_settings
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_settings();
